runtime: python27
api_version: 1
threadsafe: true

service: python27-create-token

handlers:
- url: /.*
  script: main.app

libraries:
- name: ssl
  version: latest

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'true'
