runtime: python27
api_version: 1
threadsafe: true

service: python27-base

handlers:
- url: /.*
  script: main.app

libraries:
- name: flask
  version: "0.12"

  #basic_scaling:
  #max_instances: 1
  #idle_timeout: 10m
automatic_scaling:
  #min_instances: 2
  min_idle_instances: 3
