runtime: python37

service: python37-vpc-access

handlers:
- url: /.*
  script: auto
  secure: always

vpc_access_connector:
  name: "projects/grauj-gcp/locations/us-central1/connectors/gae-us-central"

env_variables:
  _MEMORYSTORE_INSTANCE: gae-redis
  _CLOUD_SQL_INTSANCE:   mysql-internal
  _COMPUTE_INSTANCE:     ce-vm-internal

basic_scaling:
  max_instances: 1
  idle_timeout:  20m


